Add support for bazel buildsystem
ignitionrobotics/ign-transport pull request #196
Opened 2020-11-06 21:12 UTC by mjcarroll

2020-11-12 04:44 UTC, mahiuchun commented on BUILD.bazel
> +ign_config_header(
this rule is not working for me; I got `KeyError: 'Missing definition for PROJECT_NAME'`.

2020-11-12 17:52 UTC, JShep1 requested changes
I did need to add that one line to make it compatible with `ign_tools`

Additionally, is the version of `zmq` brought in by `ign_bazel` correct?  I'm getting the error ```ERROR: /home/john/.cache/bazel/_bazel_john/21b88e8e078a969a58c981cbbc88b951/external/zmq/BUILD.bazel:3:11: @zmq//:zmq: missing input file 'external/zmq/zmq_addon.hpp', owner: '@zmq//:zmq_addon.hpp'

ERROR: /home/john/.cache/bazel/_bazel_john/21b88e8e078a969a58c981cbbc88b951/external/zmq/BUILD.bazel:3:11 1 input file(s) do not exist```

Are you seeing anything like this?

2020-11-12 17:52 UTC, JShep1 commented on BUILD.bazel
> +) for src in test_sources]
Think this might need a `exports_files(["src/cmd/cmdtransport.rb.in"])` for `ign_tools`

2020-11-17 20:25 UTC, mahiuchun commented on BUILD.bazel
> +    "IGNITION_FEATURES",
Just want to point out `IGNITION_FEATURES` is depending on https://github.com/ignitionrobotics/ign-bazel/pull/28

2020-11-17 20:26 UTC, mjcarroll commented
> Additionally, is the version of zmq brought in by ign_bazel correct?

Maybe it's because I'm on focal? I believe that header can be safely removed in this case.

2020-11-17 20:27 UTC, mjcarroll commented on BUILD.bazel
> +ign_config_header(
I'm not sure why that would be the case?  It's the same as the other locations that it is used.  Is you `ign-bazel` at the lastest?

2020-11-17 20:37 UTC, mahiuchun commented on BUILD.bazel
> +ign_config_header(
ign-bazel with https://github.com/ignitionrobotics/ign-bazel/pull/28 works. otherwise I get the above-mentioned error.

2020-11-17 20:56 UTC, mjcarroll commented on BUILD.bazel
> +    "IGNITION_FEATURES",
Acknowledged

2020-11-17 22:04 UTC, JShep1 approved these changes

2020-11-17 22:04 UTC, JShep1 commented
LGTM, builds fine

2020-11-17 22:24 UTC, JShep1 commented
> > Additionally, is the version of zmq brought in by ign_bazel correct?
> 
> Maybe it's because I'm on focal? I believe that header can be safely removed in this case.

Builds fine now on Bionic with all tests green.

2020-11-18 01:41 UTC, chapulina commented on log/src/Log_TEST.cc
>  TEST(Log, OpenCorruptDatabase)
We shouldn't be disabling tests. Is there a plan to make this test work before merging the PR?

2020-11-18 01:46 UTC, mjcarroll commented on log/src/Log_TEST.cc
>  TEST(Log, OpenCorruptDatabase)
Yes, it will be restored, I believe I commented this out when it was generally not working on focal.  I will verify.

2021-04-15 22:37 UTC, mahiuchun approved these changes

2021-08-17 00:43 UTC, chapulina requested changes
Tests need to be uncommented before merging.

2021-11-12 18:01 UTC, chapulina commented
I believe this PR is outdated and not being worked on. Please reopen if this starts being worked on again.

2021-11-12 18:01 UTC, closed without merging