Configurable IP address and port for discovery
ignitionrobotics/ign-transport pull request #200
Opened 2020-11-12 22:14 UTC by caguero

See issue #192.

How to test it:

Run the `example/publisher` with:

```
IGN_DISCOVERY_MULTICAST_IP=239.255.0.7 IGN_DISCOVERY_MSG_PORT=11000 IGN_DISCOVERY_SRV_PORT=11001 IGN_VERBOSE=1 ./publisher
```

And the `example/subscriber` with:

```
IGN_DISCOVERY_MSG_PORT=11000 IGN_DISCOVERY_SRV_PORT=11001 ./subscriber
```

You should receive the messages as expected. Then, run:

```
./subscriber
```

And you shouldn't get any messages.

2020-11-16 23:59 UTC, nkoenig requested changes

2020-11-16 23:59 UTC, nkoenig commented on tutorials/20_env_variables.md
> +    discovery messages.
Can you add the default IP, or indicate how a user can get access to the default IP?

The same goes for the two new port numbers.

2020-11-19 17:58 UTC, caguero commented on tutorials/20_env_variables.md
> +    discovery messages.
Thanks, added in 34f8476.

2020-12-17 00:04 UTC, nkoenig approved these changes

2020-12-17 01:43 UTC, chapulina reviewed
Just left some high-level comments

2020-12-17 01:43 UTC, chapulina commented on include/ignition/transport/Discovery.hh
> +                        const std::string &_ip,
Is it worth it tick-tocking this? Like adding a new constructor, and using a default value with this contructor?

2020-12-17 01:43 UTC, chapulina commented on include/ignition/transport/NodeShared.hh
We should consider PIMPLizing this class

2020-12-17 01:43 UTC, chapulina commented on log/src/Recorder.cc
> +    std::unique_ptr<MsgDiscovery>(new MsgDiscovery(
Could you use `std::make_unique`?

2020-12-17 01:43 UTC, chapulina commented on src/NodeShared.cc
> +    catch (std::invalid_argument &_e)
`_e` is not used, I think it can be omitted

2020-12-23 15:22 UTC, caguero commented on include/ignition/transport/Discovery.hh
> +                        const std::string &_ip,
We could but honestly I don't think it's worth it because this class is mainly internal.

2020-12-23 15:29 UTC, caguero commented on log/src/Recorder.cc
> +    std::unique_ptr<MsgDiscovery>(new MsgDiscovery(
> Could you use `std::make_unique`?

Thanks! b8fcb21

2020-12-23 15:29 UTC, caguero commented on src/NodeShared.cc
> +    catch (std::invalid_argument &_e)
> `_e` is not used, I think it can be omitted

Removed in b8fcb21.

2020-12-23 15:30 UTC, caguero commented on include/ignition/transport/NodeShared.hh
> We should consider PIMPLizing this class

Maybe I can start working on it on a separate branch to see if there are any issues if sounds reasonable.

2020-12-23 15:49 UTC, caguero commented
@osrf-jenkins run tests please.

2020-12-23 16:34 UTC, caguero commented
@osrf-jenkins run tests please.

2020-12-23 17:35 UTC, chapulina commented on include/ignition/transport/Discovery.hh
> +                        const std::string &_ip,
Oh I see. Maybe we can stop installing it in Edifice?

2020-12-28 17:26 UTC, caguero commented on include/ignition/transport/Discovery.hh
> +                        const std::string &_ip,
> Oh I see. Maybe we can stop installing it in Edifice?

Sorry, strictly speaking is not internal because if you include `Node.hh`, it will be recursively included eventually. What I mean is that it's very uncommon that someone will directly use `Discovery.hh` as it's functionality is kind of an internal detail of the library.

2020-12-28 19:11 UTC, chapulina commented on include/ignition/transport/Discovery.hh
> +                        const std::string &_ip,
Ok, got it. Maybe in the future we can move it to a `detail` directory to make this clear to downstream users. I wouldn't be surprised if someone is using this header for something weird, but if we explicitly move it to detail at least we're not committing to tick-tock.

2020-12-28 19:51 UTC, chapulina approved these changes
I haven't tried it, but it looks reasonable to me :+1:

2020-12-30 15:19 UTC, merged