Errno
ignitionrobotics/ign-transport pull request #254
Opened 2021-08-10 19:03 UTC by caguero

Use `errno` to show additional error information.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-08-10 19:05 UTC, iche033 approved these changes

2021-08-10 19:33 UTC, mjcarroll approved these changes

2021-08-10 20:38 UTC, ahcorde requested changes
DCO ?

2021-08-10 23:06 UTC, chapulina commented
> DCO ?

The DCO checker doesn't act well when the PR is targeted at the wrong branch and then updated. It looks like it's a false-negative to me.

2021-08-10 23:25 UTC, nkoenig approved these changes

2021-08-12 15:39 UTC, nkoenig commented
@caguero we are clear to get this in and make a release.

2021-08-12 15:48 UTC, ahcorde approved these changes

2021-08-12 15:49 UTC, merged