Try USER variable to retrieve the username.
ignitionrobotics/ign-transport pull request #282
Opened 2021-12-17 17:14 UTC by iwanders

# 🦟 Bug fix

## Summary
This resolves a situation where gazebo is endlessly spamming:
```
Error getting username: no matching password record.
```
In our case, this triggered because a system was configured with ldap, but at runtime the `libnss_systemd` library wasn't available. This meant the user name lookup through ldap failed, and the fallback by reading it from `/etc/passwd` didn't work as the user wasn't present there. It can probably be reproduced by making the `getpwuid_r` always fail.

Basically, all this complexity can be removed by just checking the `$USER` environment variable. That is unlikely to fail on any linux system. I left the old behaviour in place as a fallback for if `USER` is not set, but I can't think of a situation where that would be.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests -> there's one that checks if the user name is empty [here](https://github.com/ignitionrobotics/ign-transport/blob/a4a946086a5d2180f918675d8678a778451de37a/src/NetUtils_TEST.cc#L34)
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2021-12-20 16:40 UTC, caguero requested changes

2021-12-20 16:40 UTC, caguero commented on src/NetUtils.cc
> +    // First, try to get the username through the standard environment variable for it.
Thanks for the patch!

There's a style checker complain at this line. Could you make it <= 80 characters please?

2021-12-20 17:03 UTC, iwanders commented on src/NetUtils.cc
> +    // First, try to get the username through the standard environment variable for it.
Certainly, should be fixed now.

2021-12-31 17:47 UTC, caguero approved these changes
It looks good to me, thanks for the patch!

2021-12-31 17:48 UTC, caguero requested changes
Well, one little request. Could you rename `user_variable` to `userVariable` to be consistent with our style?

2021-12-31 17:52 UTC, iwanders commented
@caguero, certainly, I've pushed a new commit where we use `userVariable` instead of `user_variable`. So used to the ros styleguide that I didn't even think of checking whether the variable name I used matched the style guide. Sorry about that.

2022-01-07 14:25 UTC, caguero approved these changes

2022-01-07 14:25 UTC, merged